name: Build and Deploy Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Download Zola
        run: curl -fLsS "https://github.com/getzola/zola/releases/download/v0.19.1/zola-v0.19.1-x86_64-unknown-linux-gnu.tar.gz" | tar xzf - -C /usr/local/bin
      - name: Verify Zola binary
        run: echo "5a08302389d1ac6a54391984d414eba01b2b7b23d9ab410f51e87756ed0563bb  /usr/local/bin/zola" | shasum -a 256 -b -c --strict
      - name: Modify URL
        if: github.repository != 'Les-Artistes-Inn/LesArtistesInn.com'
        run: sed -i 's/lesartistesinn.com/${{ secrets.CURRENT_URL }}\/LesArtistesInn.com/g' config.toml
      - name: Build website
        run: zola build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
          name: github-pages
          retention-days: 1
  deploy:
    if: github.repository != 'Les-Artistes-Inn/LesArtistesInn.com'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  deploy-prod:
    if: github.repository == 'Les-Artistes-Inn/LesArtistesInn.com'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
      - name: Unzip artifact
        run: mkdir public; tar -xvf artifact.tar -C public
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME }}
      - name: Delete old deployments
        run: |-
          API_URL="https://api.cloudflare.com/client/v4/accounts/$ACCOUNT_ID/pages/projects/$PROJECT_NAME/deployments"
          response=$(curl -s -H "Authorization: Bearer $API_TOKEN" "$API_URL")
          index=0
          echo "$response" | jq -c '.result[] | {id: .id, created_on: .created_on}' | while read -r deployment; do
            deployment_id=$(echo "$deployment" | jq -r '.id')
            deployment_date=$(echo "$deployment" | jq -r '.created_on')
            if [[ "$index" -eq 0 ]]; then
              echo "Skipping active deployment $deployment_id from $deployment_date"
            else
              echo "Deleting deployment $deployment_id from $deployment_date"
              curl -s -X DELETE -H "Authorization: Bearer $API_TOKEN" "$API_URL/$deployment_id"
            fi
            index=$((index+1))
          done
        env:
          ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          PROJECT_NAME: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}